spring.application.name=demo


# Expose the refresh endpoint over HTTP
management.endpoints.web.exposure.include=refresh

# Disable the look-up for a remote config server (enables local file usage)
spring.cloud.config.enabled=false

# Example custom property to test auto-reload
app.welcome-message=Hello from the old properties file! changed

test.message=This is a test message from the properties file changed.


property.reload=This property will be reloaded when the refresh endpoint is called. 1 changed
property.reload2=This property will be reloaded when the refresh endpoint is called. 2 changed





